version: "3.7"
services:
    app:
        build:
            args:
                user: marcus
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: sendmoney
        container_name: sendmoney-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - sendmoney

    db:
        image: mysql:5.7
        container_name: sendmoney-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICES_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - sendmoney

    nginx:
        image: nginx:1.17-alpine
        container_name: sendmoney-nginx
        restart: unless-stopped
        ports:
            - 8888:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/:/etc/nginx/conf.d
        networks:
            - sendmoney
    redis:
        image: redis:alpine
        container_name: sendmoney-redis
        ports:
        - 6379:6379
        networks:
          - sendmoney

networks:
    sendmoney:
        driver: bridge
